[project]
name = "edalize_flist"
description = "F-list plugin for Edalize, and command-line util"
version = "0.1.0"

[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
flist = "edalize.tools.flist:main"
filelist = "edalize.util.filelist:main"
